import {
  appServerSimulationConfig,
  customerSatisfactionConfig,
} from '../simulation/config'
import type { Language, TranslationKey } from '../i18n/translations'

export type MetricId =
  | 'active-users'
  | 'requests-per-second'
  | 'cpu-usage'
  | 'latency'
  | 'satisfaction'
  | 'balance'
  | 'revenue'
  | 'infrastructure-cost'
  | 'net-cash-flow'
  | 'game-time'

type LocalizedText = Record<Language, string>

export type MetricEducationDefinition = {
  id: MetricId
  labelKey: TranslationKey
  meaning: LocalizedText
  increases: readonly LocalizedText[]
  decreases: readonly LocalizedText[]
}

export type MetricEducationSnapshot = {
  activeUsers: number
  requestsPerSecond: number
  requestsPerUserPerSecond: number
  cpuUsage: number
  requestCapacity: number
  latencyMs: number
  customerSatisfaction: number
  badLatencyDurationSeconds: number
  balance: number
  revenuePerPeriod: number
  infrastructureCostPerPeriod: number
  netCashFlowPerPeriod: number
  incidentCosts: number
  gameTimeSeconds: number
  costPeriodSeconds: number
  serviceStarted: boolean
  isPaused: boolean
  isServiceOverloaded: boolean
}

export const metricEducationDefinitions: Record<
  MetricId,
  MetricEducationDefinition
> = {
  'active-users': {
    id: 'active-users',
    labelKey: 'metric.activeUsers',
    meaning: {
      en: 'People currently using the SaaS product.',
      ar: 'عدد الأشخاص الذين يستخدمون منتج البرمجيات حاليًا.',
    },
    increases: [
      { en: 'customer growth over game time', ar: 'نمو العملاء مع مرور وقت اللعبة' },
      { en: 'traffic events and campaigns', ar: 'أحداث حركة البيانات والحملات' },
    ],
    decreases: [
      { en: 'a temporary traffic event ending', ar: 'انتهاء حدث مؤقت لحركة البيانات' },
      { en: 'starting a new stage baseline', ar: 'بدء خط أساس جديد للمرحلة' },
    ],
  },
  'requests-per-second': {
    id: 'requests-per-second',
    labelKey: 'metric.requestsPerSecond',
    meaning: {
      en: 'Application requests arriving every second.',
      ar: 'عدد طلبات التطبيق التي تصل في كل ثانية.',
    },
    increases: [
      { en: 'more active users', ar: 'زيادة عدد المستخدمين النشطين' },
      { en: 'a traffic multiplier event', ar: 'حدث يضاعف حركة البيانات' },
    ],
    decreases: [
      { en: 'fewer active users', ar: 'انخفاض عدد المستخدمين النشطين' },
      { en: 'a traffic event ending', ar: 'انتهاء حدث حركة البيانات' },
    ],
  },
  'cpu-usage': {
    id: 'cpu-usage',
    labelKey: 'metric.cpuUsage',
    meaning: {
      en: 'The share of App Server processing capacity currently in use.',
      ar: 'نسبة قدرة المعالجة في خادم التطبيق المستخدمة حاليًا.',
    },
    increases: [
      { en: 'more requests reaching the server', ar: 'وصول طلبات أكثر إلى الخادم' },
      { en: 'traffic approaching server capacity', ar: 'اقتراب حركة البيانات من سعة الخادم' },
    ],
    decreases: [
      { en: 'more server capacity', ar: 'زيادة سعة الخادم' },
      { en: 'less traffic per server', ar: 'انخفاض حركة البيانات لكل خادم' },
    ],
  },
  latency: {
    id: 'latency',
    labelKey: 'metric.latency',
    meaning: {
      en: 'Time required for the system to respond to a request.',
      ar: 'الوقت الذي يحتاجه النظام للاستجابة إلى الطلب.',
    },
    increases: [
      { en: 'high server utilization', ar: 'ارتفاع استخدام الخادم' },
      { en: 'traffic exceeding capacity', ar: 'تجاوز حركة البيانات للسعة' },
    ],
    decreases: [
      { en: 'more capacity becoming available', ar: 'توفر سعة أكبر' },
      { en: 'traffic load decreasing', ar: 'انخفاض حمل حركة البيانات' },
    ],
  },
  satisfaction: {
    id: 'satisfaction',
    labelKey: 'metric.satisfaction',
    meaning: {
      en: 'How satisfied customers are with the service experience.',
      ar: 'مدى رضا العملاء عن تجربة استخدام الخدمة.',
    },
    increases: [
      { en: 'future recovery systems', ar: 'أنظمة التعافي التي ستُضاف لاحقًا' },
    ],
    decreases: [
      { en: 'latency staying high', ar: 'استمرار زمن الاستجابة المرتفع' },
      { en: 'severe service outages', ar: 'انقطاعات الخدمة الشديدة' },
    ],
  },
  balance: {
    id: 'balance',
    labelKey: 'metric.balance',
    meaning: {
      en: 'Company cash available for infrastructure decisions.',
      ar: 'أموال الشركة المتاحة لاتخاذ قرارات البنية التحتية.',
    },
    increases: [
      { en: 'revenue exceeding infrastructure costs', ar: 'تجاوز الإيرادات لتكاليف البنية التحتية' },
    ],
    decreases: [
      { en: 'infrastructure costs exceeding revenue', ar: 'تجاوز تكاليف البنية التحتية للإيرادات' },
      { en: 'upgrades and incident penalties', ar: 'الترقيات وغرامات الحوادث' },
    ],
  },
  revenue: {
    id: 'revenue',
    labelKey: 'metric.revenue',
    meaning: {
      en: 'Income generated by active, satisfied customers each period.',
      ar: 'الدخل الناتج عن العملاء النشطين والراضين في كل فترة.',
    },
    increases: [
      { en: 'more active users', ar: 'زيادة المستخدمين النشطين' },
      { en: 'strong customer satisfaction', ar: 'ارتفاع رضا العملاء' },
    ],
    decreases: [
      { en: 'customer satisfaction falling', ar: 'انخفاض رضا العملاء' },
      { en: 'fewer active users', ar: 'انخفاض المستخدمين النشطين' },
    ],
  },
  'infrastructure-cost': {
    id: 'infrastructure-cost',
    labelKey: 'metric.infrastructureCost',
    meaning: {
      en: 'Operating cost of the currently deployed infrastructure each period.',
      ar: 'تكلفة تشغيل البنية التحتية المنشورة حاليًا في كل فترة.',
    },
    increases: [
      { en: 'larger server tiers', ar: 'استخدام فئات خوادم أكبر' },
      { en: 'adding infrastructure resources', ar: 'إضافة موارد بنية تحتية' },
    ],
    decreases: [
      { en: 'using fewer or smaller resources', ar: 'استخدام موارد أقل أو أصغر' },
    ],
  },
  'net-cash-flow': {
    id: 'net-cash-flow',
    labelKey: 'metric.netCashFlow',
    meaning: {
      en: 'Revenue minus infrastructure cost for one economy period.',
      ar: 'الإيرادات مطروحًا منها تكلفة البنية التحتية لفترة مالية واحدة.',
    },
    increases: [
      { en: 'higher revenue', ar: 'ارتفاع الإيرادات' },
      { en: 'lower infrastructure cost', ar: 'انخفاض تكلفة البنية التحتية' },
    ],
    decreases: [
      { en: 'lower satisfaction reducing revenue', ar: 'انخفاض الرضا وتقليل الإيرادات' },
      { en: 'higher infrastructure cost', ar: 'ارتفاع تكلفة البنية التحتية' },
    ],
  },
  'game-time': {
    id: 'game-time',
    labelKey: 'metric.gameTime',
    meaning: {
      en: 'Time elapsed since the current stage service started.',
      ar: 'الوقت المنقضي منذ بدء خدمة المرحلة الحالية.',
    },
    increases: [
      { en: 'the simulation running at 1x, 2x, or 4x', ar: 'تشغيل المحاكاة بسرعة 1x أو 2x أو 4x' },
    ],
    decreases: [
      { en: 'it resets only when a stage starts or restarts', ar: 'يُعاد ضبطه فقط عند بدء المرحلة أو إعادتها' },
    ],
  },
}

export function getMetricCurrentReason(
  metricId: MetricId,
  snapshot: MetricEducationSnapshot,
  language: Language,
) {
  const text = (en: string, ar: string) => (language === 'ar' ? ar : en)

  if (!snapshot.serviceStarted) {
    return text(
      'This metric is waiting for a valid Users → App Server → Database path.',
      'ينتظر هذا المقياس مسارًا صالحًا: المستخدمون ← خادم التطبيق ← قاعدة البيانات.',
    )
  }

  switch (metricId) {
    case 'active-users':
      return text(
        `${snapshot.activeUsers} users are active at ${snapshot.gameTimeSeconds} game seconds.`,
        `يوجد ${snapshot.activeUsers} مستخدمًا نشطًا عند ${snapshot.gameTimeSeconds} ثانية لعب.`,
      )
    case 'requests-per-second':
      return text(
        `${snapshot.activeUsers} users × ${snapshot.requestsPerUserPerSecond} requests each = ${snapshot.requestsPerSecond.toFixed(1)} requests/sec.`,
        `${snapshot.activeUsers} مستخدمًا × ${snapshot.requestsPerUserPerSecond} طلب لكل مستخدم = ${snapshot.requestsPerSecond.toFixed(1)} طلب/ثانية.`,
      )
    case 'cpu-usage':
      if (snapshot.isServiceOverloaded) {
        return text(
          'CPU is capped at 100% because traffic exceeds server capacity.',
          'استخدام المعالج محدود عند 100% لأن حركة البيانات تتجاوز سعة الخادم.',
        )
      }
      return text(
        `The App Server is processing ${snapshot.requestsPerSecond.toFixed(1)} of ${snapshot.requestCapacity.toFixed(1)} requests/sec capacity.`,
        `يعالج خادم التطبيق ${snapshot.requestsPerSecond.toFixed(1)} من سعة ${snapshot.requestCapacity.toFixed(1)} طلب/ثانية.`,
      )
    case 'latency':
      if (snapshot.isServiceOverloaded) {
        return text(
          'Latency is high because the App Server is overloaded.',
          'زمن الاستجابة مرتفع لأن خادم التطبيق تحت حمل زائد.',
        )
      }
      return text(
        `Latency is ${snapshot.latencyMs} ms while CPU uses ${snapshot.cpuUsage.toFixed(1)}% of capacity.`,
        `زمن الاستجابة ${snapshot.latencyMs} مللي ثانية مع استخدام ${snapshot.cpuUsage.toFixed(1)}% من قدرة المعالج.`,
      )
    case 'satisfaction':
      return snapshot.badLatencyDurationSeconds >=
        customerSatisfactionConfig.sustainedBadLatencySeconds
        ? text(
            'Satisfaction is decreasing because latency has remained high.',
            'ينخفض رضا العملاء لأن زمن الاستجابة ظل مرتفعًا.',
          )
        : text(
            'Satisfaction is stable because latency has not remained above the harmful threshold.',
            'رضا العملاء مستقر لأن زمن الاستجابة لم يبقَ فوق الحد الضار.',
          )
    case 'balance':
      return snapshot.netCashFlowPerPeriod < 0
        ? text(
            'Balance is decreasing because infrastructure cost is higher than revenue.',
            'ينخفض الرصيد لأن تكلفة البنية التحتية أعلى من الإيرادات.',
          )
        : text(
            'Balance grows each period because revenue covers infrastructure cost.',
            'يزداد الرصيد كل فترة لأن الإيرادات تغطي تكلفة البنية التحتية.',
          )
    case 'revenue':
      return text(
        `Revenue reflects ${snapshot.activeUsers} active users at ${snapshot.customerSatisfaction.toFixed(1)}% satisfaction.`,
        `تعكس الإيرادات ${snapshot.activeUsers} مستخدمًا نشطًا مع رضا بنسبة ${snapshot.customerSatisfaction.toFixed(1)}%.`,
      )
    case 'infrastructure-cost':
      return text(
        `Deployed resources cost ${snapshot.infrastructureCostPerPeriod} credits every ${snapshot.costPeriodSeconds} seconds.`,
        `تكلف الموارد المنشورة ${snapshot.infrastructureCostPerPeriod} رصيدًا كل ${snapshot.costPeriodSeconds} ثانية.`,
      )
    case 'net-cash-flow':
      return snapshot.netCashFlowPerPeriod < 0
        ? text(
            'Cash flow is negative because current costs exceed revenue.',
            'التدفق النقدي سالب لأن التكاليف الحالية تتجاوز الإيرادات.',
          )
        : text(
            'Cash flow is positive because revenue exceeds current costs.',
            'التدفق النقدي موجب لأن الإيرادات تتجاوز التكاليف الحالية.',
          )
    case 'game-time':
      return snapshot.isPaused
        ? text('Game time is paused.', 'وقت اللعبة متوقف مؤقتًا.')
        : text('Game time advances with the selected speed.', 'يتقدم وقت اللعبة حسب السرعة المحددة.')
  }
}

export function getCpuTrend(cpuUsage: number) {
  if (cpuUsage >= appServerSimulationConfig.highCpuThreshold) {
    return 'high'
  }
  if (cpuUsage >= appServerSimulationConfig.elevatedCpuThreshold) {
    return 'elevated'
  }
  return 'normal'
}

export type LiveMetricCause = {
  trend: 'up' | 'down'
  text: string
}

export function getLiveMetricCause(
  metricId: MetricId,
  snapshot: MetricEducationSnapshot,
  language: Language,
): LiveMetricCause | null {
  if (!snapshot.serviceStarted) {
    return null
  }

  const text = (en: string, ar: string) => (language === 'ar' ? ar : en)

  switch (metricId) {
    case 'cpu-usage': {
      const cpuTrend = getCpuTrend(snapshot.cpuUsage)
      if (snapshot.isServiceOverloaded) {
        return {
          trend: 'up',
          text: text('Server overloaded', 'الخادم تحت حمل زائد'),
        }
      }
      if (cpuTrend === 'high' || cpuTrend === 'elevated') {
        return {
          trend: 'up',
          text: text('Traffic near capacity', 'الحركة تقترب من السعة'),
        }
      }
      return null
    }
    case 'latency':
      return snapshot.latencyMs > customerSatisfactionConfig.badLatencyThresholdMs
        ? {
            trend: 'up',
            text: text('High server load', 'حمل الخادم مرتفع'),
          }
        : null
    case 'satisfaction':
      return snapshot.badLatencyDurationSeconds >=
        customerSatisfactionConfig.sustainedBadLatencySeconds
        ? {
            trend: 'down',
            text: text('Latency stayed high', 'استمر زمن الاستجابة مرتفعًا'),
          }
        : null
    case 'balance':
      return snapshot.netCashFlowPerPeriod < 0
        ? {
            trend: 'down',
            text: text('Cost exceeds revenue', 'التكلفة تتجاوز الإيرادات'),
          }
        : null
    default:
      return null
  }
}
